# -*- coding: utf-8 -*-
"""
/***************************************************************************
 flood_analysis
                                 A QGIS plugin
 complemento de analisis de inundaciones
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-02
        copyright            : (C) 2025 by Junior Calvo
        email                : junior.calvo04@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load flood_analysis class from file flood_analysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_analysis_module import flood_analysis
    return flood_analysis(iface)
